INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Barbate','Andalucía',11160);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Jerez','Andalucía',11401);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Málaga','Andalucía',29001);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Sevilla','Andalucía',41001);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Madrid','Comunidad de Madrid',28001);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Toledo','Castilla la Mancha',45001);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Mijas','Andalucía',29650);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('País Vasco','Abaltzisketa',20269);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('La Coruña','Galicia',15001);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Losar de la Vera','Extremadura',10460);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Cáceres','Extremadura',10001);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Córdoba','Andalucía',14001);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Badajoz','Extremadura',06001);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Conil de la Frontera','Andalucía',11140);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Chiclana','Andalucía',11130);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('San Fernando','Andalucía',11100);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Logroño','La Rioja',26001);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Valladolid','Castilla y León',47001);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Ceuta','n/a',51001);
INSERT INTO ciudad (nombre, comunidad_auto, cod_postal) VALUES ('Melilla','n/a',52001);
